### ISSUE TITLE
Is there a way to convert space seperated words to camelcase?

### ISSUE THREAD

**Issue by Petah** [ICanBoogie/Inflector#10]

**Comment by olvlvl** [comment]
To convert space separated words to camelcase you first need to replace white spaces by hyphens, as follows:

```php
echo $inflector->camelize(preg_replace('/\s+/', '-', "A phrase to camel case"))
```

**Comment by Petah** [comment]
Thanks, that what I ended up using, would be nice to have helper method though ;)

**Comment by olvlvl** [comment]
That's an idea :)
