### ISSUE TITLE
Pluralize should take a value to determine whether to pluralize or not

### ISSUE THREAD

**Issue by smartmailer-marcus** [ICanBoogie/Inflector#14]
Hi

This is more of a feature request, or something to save me having to do  a lot of "if" statements around my app. It may not be your intention for the library. And it may not be as simple as this...

```
/**
 * Returns the plural form of the word in the string.
 *
 * <pre>
 * $this->pluralize('post');       // "posts"
 * $this->pluralize('children');   // "child"
 * $this->pluralize('sheep');      // "sheep"
 * $this->pluralize('words');      // "words"
 * $this->pluralize('CamelChild'); // "CamelChild"
 * </pre>
 *
 * @param string $word
 * @param int $number    used to determine whether to pluralize or not
 *
 * @return string
 */
public function pluralize($word, $number = 2)
{
    if($number < 2) {
        return $word;
    }
    return $this->apply_inflections($word, $this->inflections->plurals);
}
```

Regards
Marcus

**Comment by olvlvl** [comment]
Hi Marcus,

Thanks for your suggestion, but it's more the job of an i18n library to decide whether or not to pluralize a word, and use the inflector to do that. [ICanBoogie/CLDR](https://github.com/ICanBoogie/CLDR#plurals) might help you in that regard. Comparing with `2` seems simple enough, but I have no idea if it's accurate, there's so many different rules, I'd rather not implement this.
