### ISSUE TITLE
Switch to enable words to retain deliberate capitals when camelizing

### ISSUE THREAD

**Issue by calcinai** [ICanBoogie/Inflector#15]
It'd be nice to be able to retain partially camelized words when calling this method.  For example, I'm working with this:

```
/defintions/securityDefinitions
```

Which after camelizing, results in 

```
\Definitions\Securitydefinitions
```

Losing the capital `D`.  The current workaround is to `underscore()` it first, like this:

``` php
$class = $inflector->camelize($inflector->underscore($fragment));
```

I assume it was a deliberate choice to use `capitalize()` over `ucfirst()`, but in some cases (like above) I think it's less desirable.  What do you think?

**Comment by olvlvl** [comment]
I think you have a good point. Have you tried implementing a fix?

**Comment by calcinai** [comment]
I absolutely can - would you call it a fix to make it the default behaviour, or should I implement a switch?

**Comment by olvlvl** [comment]
It would be a fix to the current behavior. I checked Doctrine's inflector, and that's what it does.
