### ISSUE TITLE
Pluralize french not totally working

### ISSUE THREAD

**Issue by VincentMolinie** [ICanBoogie/Inflector#18]
If I put something like: "Objet de Marine" it returns "Objet de Marines" it should be in that case "Objets de Marine". I'm doing a PR for that

**Comment by olvlvl** [comment]
Thanks Vincent, but the inflector is working on words, not phrases. You probably need a higher implementation for that.

**Comment by olvlvl** [comment]
@VincentMolinie I'm closing this issue for now. Feel free to open it again if you have any update.
