### ISSUE TITLE
Pluralize error

### ISSUE THREAD

**Issue by ssi-anik** [ICanBoogie/Inflector#20]
Hello there, Can you please have a look at the attached image? I am facing an error.
BTW, Thanks for the package. :)
![screenshot from 2017-04-24 16-21-49](https://cloud.githubusercontent.com/assets/2676602/25332965/445ebeb4-290a-11e7-91e2-066a2b70de65.png)

**Comment by olvlvl** [comment]
Interesting, especially since "category" and "energy" or both working…

**Comment by ssi-anik** [comment]
Thanks for your quick fix. Can you add a tag? Or Should I pull from dev-master?

**Comment by olvlvl** [comment]
Here: https://github.com/ICanBoogie/Inflector/releases/tag/v1.4.3
Thanks for reporting the bug.

**Comment by ssi-anik** [comment]
Thanks brother
