### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by tigusigalpa** [ICanBoogie/Inflector#35]
Hi. I dont have a time for now about commit, but at PHP 7.4 there is an error

> Array and string offset access syntax with curly braces is deprecated in <b>vendor/icanboogie/inflector/lib/inflections.php</b> on line <b>350</b>

Just replace to

> $r0 = $rule[0];

**Comment by olvlvl** [comment]
Are you using the last version? This was fixed in Octobre last year:

https://github.com/ICanBoogie/Inflector/commit/9fa7e8fcf7a6ac06257ae77e9aa2ec90925b4327#diff-e05e345dd35912cbefe97e359b05f388L350-L351
