### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by RickKukiela** [ICanBoogie/Inflector#36]
Is there any backward breaking changes when moving form v1.5.0 to v2?

I was going to submit a PR regarding the use {} to access array key zero in the `human()` method of the `inflectors.php` file however this appears to be fixed in v2.

Anyway, I'd like to know if there is anything I should be aware of before I upgrade.

Thanks!

**Comment by olvlvl** [comment]
v2 requires PHP 7.1 and I added type hints everywhere, plus fixed some little things for PHP 7.4. It should be safe to update if you use PHP 7.1.

**Comment by olvlvl** [comment]
@RickKukiela I'm closing this issue. Please re-open it if you're having trouble with v2.

**Comment by RickKukiela** [comment]
Super late on noticing you replied to this - as you can see it was not an emergency haha, thanks for the reply :)

**Comment by olvlvl** [comment]
BTW, the latest version is compatible with PHP 8.0 ;)
