### ISSUE TITLE
Language support: Polish

### ISSUE THREAD

**Issue by nmapx** [ICanBoogie/Inflector#37]
Do you plan to add more languages to the lib? I would really use it, especially Polish.

**Comment by olvlvl** [comment]
Hi @nmapx, it's easy to add languages to the library, it's a file in here: https://github.com/ICanBoogie/Inflector/tree/master/lib/inflections. Now, writing the regexp for the inflections is the hard part. If you know your way around regexp and know some rules for Polish, maybe you can get something started?

**Comment by nmapx** [comment]
I was also thinking about that. Alright! I'll try to find some spare time to start with PL lang.

**Comment by olvlvl** [comment]
It doesn't have to be perfect. If you can start with the most important rule(s), it can be improved in time.
