### ISSUE TITLE
titleize capitalising ‘a’, ‘of’, ‘the’

### ISSUE THREAD

**Issue by joshuabaker** [ICanBoogie/Inflector#7]
How might these be excluded?

https://github.com/danielstjules/Stringy#titleize-array-ignore

**Comment by olvlvl** [comment]
Would this be satisfying?

https://github.com/ICanBoogie/Inflector/tree/filtering_titleize

**Comment by joshuabaker** [comment]
Cheers, Olivier! :relaxed:

That’s working with the exception of the “X-Men: The Last Stand”. The [tests](https://github.com/ICanBoogie/Inflector/commit/b306953567c0d8e405dc20da397d07dc9961b8ba#diff-5872e14c4bd6b3f393e0acdf70c4eedbR419) are technically incorrect, allowing/checking for a lowercase “The” and unhyphenated “X-Men”.

To resolve the capitalisation of “The” I might split the string by various characters (i.e. full-stop, colons, and dashes) before parsing.

The hyphen should really be maintained in every instance that I can think of. Was that intentionally removed?

*P.s. I’d submit a pull request but I’m a bit pushed for time this week. Give me a shout if I can help.*

**Comment by olvlvl** [comment]
Hi @joshuabaker, we forgot to celebrate the anniversary of this issue ;) I'll close it for now. Feel free to open it again.
